### 회원가입
POST http://localhost:8080/api/v1/auth/local/signup
X-Device-Id: dev-123
Content-Type: application/json
Accept: application/json

{
  "email": "a1@a.com",
  "password": "password123@",
  "phoneNumber": "010-1234-5678",
  "gender": "MALE",
  "locale": "ko-KR",
  "nickname": "soo_01",
  "name": "홍길동",
  "profileImageUrl": "https://example.com/profile.png",
  "thumbnailImageUrl": "https://example.com/thumb.png",
  "birthyear": "1998",
  "birthday": "02-07"
}

### 로그인 (토큰 변수 저장)
# @name login
POST http://localhost:8080/api/v1/auth/local/login
X-Device-Id: dev-123
Content-Type: application/json
Accept: application/json

{
  "email": "a1@a.com",
  "password": "password123@"
}

> {%
    // 로그인 응답 예시:
    // { "result": "OK", "data": { "accessToken": "...", "refreshToken": "...", ... } }
    client.global.set("accessToken", response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}

### refresh (회전: 새 access + 새 refresh 발급) + 변수 업데이트
# @name refresh
POST http://localhost:8080/api/v1/auth/local/token/refresh
X-Device-Id: dev-123
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "ce0644fd734e45a5a1ad04836a91c4dfb498d87055b74e7894f3f9a4b0421ece"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}


### logout (현재 access denylist + refresh revoke)
POST http://localhost:8080/api/v1/auth/local/logout
X-Device-Id: dev-123
Authorization: Bearer eyJraWQiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhMUBhLmNvbSIsInVpZCI6MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6InNvby1hdXRoLXNlcnZpY2UiLCJleHAiOjE3NzE0ODEzNjYsImlhdCI6MTc3MTQ4MDQ2NiwianRpIjoiNDBkOGI3YzItM2IyOS00YzhmLTg3MTMtOGE2ZjE2ZDFiNTU2In0.g_Ylbmk30MFTTcbNDed60LOIN7eWSH7mDLeiHKxToApbvX6qNrxawxDpGam6ww0_yKASSfNW73kikrLQVFGozA9OcNcMXEDHDE2w5Nbh3tqK-4MWQnQdZ1oQAtvF5vSQkb_gP0aYeYQQC7ADFXZrZqFRcLOR2DGsclpulJl7uviBKnKc5RBWOhwcb5gk6FyE29l34gc31qJbKH2a6gHdxwQt0JzeUkyhSPawpu_roVHFZgD1_N4lUGIy0ZKWqqyXiB8Yw53oHWJSd8NaT47Nv9JemlJJrVwfvRCRIJLsq7FbP5AZi7HE7cXx6H8MhgwoIPNYNa6irkEDyyj4_ZVaUA
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "ce0644fd734e45a5a1ad04836a91c4dfb498d87055b74e7894f3f9a4b0421ece",
  "logoutAll": false
}
